export const INGREDIENTS_GET = "INGREDIENTS_GET";
export const INGREDIENTS_GET_FAIL = "INGREDIENTS_GET_FAIL";
export const INGREDIENTS_GET_OK = "INGREDIENTS_GET_OK";

export const INGREDIENT_SELECT = "INGREDIENT_SELECT";
export const SELECTED_INGREDIENT_DELETE = "SELECTED_INGREDIENT_DELETE";

export const INGREDIENT_ADD = "INGREDIENT_ADD";
export const INGREDIENT_DELETE = "INGREDIENT_DELETE";
export const INGREDIENTS_DELETE = "INGREDIENTS_DELETE";

export const INGREDIENT_MOVE = "INGREDIENT_MOVE";

export const ORDER_DETAILS_GET = "ORDER_DETAILS_GET";
export const ORDER_DETAILS_GET_FAIL = " ORDER_DETAILS_GET_FAIL";
export const ORDER_DETAILS_GET_OK = "ORDER_DETAILS_GET_OK";
export const ORDER_DETAILS_DELETE = "ORDER_DETAILS_DELETE";

export const SET_ORDER_DETAILS_MODAL_OPEN = "SET_ORDER_DETAILS_MODAL_OPEN";
export const SET_INGREDIENTS_MODAL_OPEN = "SET_INGREDIENTS_MODAL_OPEN";
